---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: atomix
# description will be included in the image's metadata
description: Bazzite with some modifications.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bazzite
image-version: latest # You can pin to a specific version of Fedora as well

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
      copr:
        - atim/starship
        - lionheartp/Hyprland
        - linuxgamerlife/lgl-dnf-helper
        - linuxgamerlife/lgl-emoji-picker
        - linuxgamerlife/lgl-vm-curator
        - linuxgamerlife/lgl-cliamp
        - theblackdon/dcli-bootc
        - imput/helium
        - faugus/faugus-launcher
        - sneexy/zen-browser
        - yalter/niri
       enable:
        - terra
    install:
      packages:
        - micro
        - starship
        - btop
        - htop
        - git
        - eza
        - zoxide
        - gh
        #- zen-browser
        - zed
        - helium-bin
        - haruna
        - faugus-launcher
        - noctalia-git
        - qt5ct
        - qt6ct
        - lgl-cliamp
        - nwg-look
        - adw-gtk3-theme
        - kitty
        - lgl-emoji-picker
        - lgl-dnf-helper
        - niri
        - sddm
    remove:
      packages: 
        - lutris
        - waydroid
        - waydroid-selinux
        - input-remapper
        - mariadb
        - mariadb-server
        - mariadb-common
        - mariadb-errmsg
        - mariadb-connector-c
        - mariadb-connector-c-config
        - mariadb-backup
        - mariadb-cracklib-password-check
        - mariadb-gssapi-server
  # Bazaar storefront (replaced by plasma-discover) + its KRunner plugin
        #- bazaar
        - krunner-bazaar
  # KDE Connect
        #- kde-connect
        #- kdeconnectd
        #- kde-connect-libs
  # ROM Properties (rp-config)
        - rom-properties
        - rom-properties-common
        - rom-properties-kf6
        - rom-properties-utils
  # Bazzite system updater
        - uupd
        - topgrade
  # Bazzite Portal (yafti welcome app)
        - bazzite-portal

  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: [] # system flatpaks we want all users to have and not remove
          #- org.mozilla.firefox
          #- org.gnome.Loupe
      - scope: user # Also add Flathub user repo, but no user packages
      
  - type: signing # this sets up the proper policy & signing files for signed images to work fully
